

[build]
    image = "ghcr.io/fly-apps/cog-whisper:latest"

[experimental]
    cmd = ["python -m cog.server.http"]

[env]
    COG_LOG_LEVEL = "debug"

[http_service]
    internal_port = 5000
    force_https = false
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0
    processes = ['app']

    [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[vm]]
    size = "performance-8x"
    memory = "16gb"
    gpu_kind = "l40s"

[[mounts]]
    source = 'data'
    destination = '/src/weights'
    initial_size = '10G'
