name: Build and Deploy

on: [workflow_dispatch]

jobs:
  build:
    name: Build Cog Image
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - uses: replicate/setup-cog@v1
          with:
            install-cuda: false
            cog-version: v0.9.4
        - run: flyctl auth docker
        - id: getApp
        - run: echo "APP_NAME=$(flyctl status --json | jq .ID)" >> $GITHUB_OUTPUT
        - run: cog push registry.fly.io/${{ steps.getApp.outputs.APP_NAME }}:latest --use-cuda-base-image false
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    deploy:
      name: Deploy Cog to Fly
      runs-on: ubuntu-latest
      needs: build
      steps:
          - uses: actions/checkout@v3
          - uses: superfly/flyctl-actions/setup-flyctl@master
          - run: flyctl deploy
            env:
              FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
