name: Build and Push

on:
    push:
      branches:
        - main
      paths-ignore:
        - '**.md'
        - '.github/**'
        - '.gitignore'
    workflow_dispatch:

jobs:
  build:
    name: Build and Push Cog Image
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - uses: replicate/setup-cog@v2
          with:
            install-cuda: false
            cog-version: v0.9.12
        - run: cog push ghcr.io/fly-apps/cog-whisper:latest --use-cuda-base-image false
