name: Build and Push Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'fly.toml'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Cog Image
        uses: replicate/setup-cog@v2
        with:
          install-cuda: false
          cog-version: v0.9.12
      - run: |
          digest=$(cog push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest --use-cuda-base-image false | grep 'digest: sha256' | awk '{ print $3 }')
          echo "digest=$digest" >> $GITHUB_ENV
                
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ env.digest }}
          push-to-registry: true
